### ISSUE TITLE
Agent-to-Agent Error message 

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-tac#214]
Implement a way to send/handle error messages to/from another participant.

## Why
During the competition, the agent keeps a counter of the next dialogue id to use with other agents. 
When an agent tries to rejoin the competition, all the counters have been zeroed. Hence, when starts negotiating, the other agents would have already seen the CFPs because of the low dialogue id, resulting in a `Decline`.

In order to fix it, instead of answering with a `Decline`, the recipient agent should answer with an error message containing the dialogue id that he expected to see. In this way, the sender agent can update his counter, and send a proper CFP.

## How
Currently, the only agent-to-agent communication is provided by the OEF Python SDK.
The different types of messages are: `CFP`, `Propose`, `Accept`, `Decline` and a general-purpose message `ByteMessage`. 
The new error message (and later agent-to-agent messages) will be built on top of `ByteMessage`, in the same fashion of the messages between agents and controller.

So we're going to need new Protobuf message definitions in `proto/tac.proto` and to update the `reactions.py` and the `negotiation_behaviours.py` modules to parse/dispatch/handle the error.

**Comment by DavidMinarsch** [comment]
Also, move all the tac related comms into a `tac` protocol.

**Comment by DavidMinarsch** [comment]
Addressed via #367
