### ISSUE TITLE
Quickstart script

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-tac#294]
**Is your feature request related to a problem? Please describe.**
During the first hackathon users struggled to connect the agent at the right time to the sandbox.

**Describe the solution you'd like**
- Provide a script to launch the sandbox and agents at the right time.
- Provide a guide which describes the order of events: start Visdom, spawn controller, spawn agents, wait to start, registration phase opens, agent connects

**Describe alternatives you've considered**
na

**Additional context**
see attachment
![IMG_5350](https://user-images.githubusercontent.com/19314578/61728337-ef0a1780-ad6c-11e9-9da6-8c1a78927628.JPG)

**Comment by DavidMinarsch** [comment]
The my agent template needs to incorporate a health check for the oef. Then once the health check passes it starts trying to register (as implemented already).

**Comment by marcofavorito** [comment]
fixed by #319
