### ISSUE TITLE
Split controller and agents image in sandbox

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-tac#307]
**Is your feature request related to a problem? Please describe.**
Currently, the sandbox runs one docker image for both the controller agent and the baseline agents (when present). However, it's hard to do benchmarking when both of them are tight together.

**Describe the solution you'd like**
A neater approach might be to have them split. 

The current Docker images run by the sandbox are:
- OEF
- Visdom server
- TAC image (for running both the controller agent and the baseline agents)

The proposed configuration will have:

The current Docker images run by the sandbox are:
- OEF
- Visdom server
- TAC image (for running the controller)
- TAC image (for running the baseline agents)

That requires to change the `sandbox/docker-compose.yml` file.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by 5A11** [comment]
This repo is being archived. Please refer to the [AEA Framework](https://github.com/fetchai/agents-aea) repo which is the new framework fo creating autonomous economic agents. There are example TAC agents in the repo as well.
