### ISSUE TITLE
Use a published TAC image in the sandbox.

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-tac#308]
**Is your feature request related to a problem? Please describe.**
To run the sandbox with `docker-compose`, it's required to build the TAC image before running `docker-compose up`. 

**Describe the solution you'd like**
If we publish the TAC docker image on some Docker repository, then `docker-compose up` would be enough, since it will automatically pull the needed images.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by marcofavorito** [comment]
Add it to `docker-compose.yml`: https://hub.docker.com/repository/docker/marcofavorito/docker-tac-develop

**Comment by 5A11** [comment]
This repo is being archived. Please refer to the [AEA Framework](https://github.com/fetchai/agents-aea) repo which is the new framework fo creating autonomous economic agents. There are example TAC agents in the repo as well.
