### ISSUE TITLE
Agents-tac error while running the github commands

### ISSUE THREAD

**Issue by ashnaeldho** [fetchai/agents-tac#411]
Hi,

According to the GitHub repo, when I follow 

Option1: Quick Start:
`pipenv shell`
`python scripts/launch.py`

I'm getting the following error:

> Traceback (most recent call last):
> File "launch.py", line 32, in <module>
>   from tac.agents.participant.v1.examples.baseline import main as participant_agent_main
>  File "/home/g2-test/Desktop/Agent-rameworks/github-repos/TAC/agents-tac/tac/agents/participant/v1/examples/baseline.py", line 29, in <module>
>    from tac.agents.participant.v1.agent import ParticipantAgent
>  File "/home/g2-test/Desktop/Agent-rameworks/github-repos/TAC/agents-tac/tac/agents/participant/v1/agent.py", line 28, in ><module>
>    from aea.channels.oef.connection import OEFMailBox
>ModuleNotFoundError: No module named 'aea.channels'

Option2: Launcher GUI:
`pipenv shell`
`python tac/gui/launcher/app.py`,
The error is:

> Traceback (most recent call last):
>  File "app.py", line 24, in <module>
>    from tac.gui.launcher import create_app
>  File "/home/g2-test/Desktop/Agent-rameworks/github-repos/TAC/agents-tac/tac/gui/launcher/__init__.py", line 37, in <module>
>    from tac.gui.launcher import home, api
>  File "/home/g2-test/Desktop/Agent-rameworks/github-repos/TAC/agents-tac/tac/gui/launcher/api/__init__.py", line 24, in <module>
>    from .resources.sandboxes import SandboxList, Sandbox
>  File "/home/g2-test/Desktop/Agent-rameworks/github-repos/TAC/agents-tac/tac/gui/launcher/api/resources/sandboxes.py", line >36, in <module>
>    from tac.platform.shared_sim_status import (
>  File "/home/g2-test/Desktop/Agent-rameworks/github-repos/TAC/agents-tac/tac/platform/shared_sim_status.py", line 29, in ><module>
>    from aea.agent import AgentState
>ImportError: cannot import name 'AgentState' from 'aea.agent' (/home/g2-test/.local/share/virtualenvs/agents-tac-lrd3GPRh/lib/python3.7/site-packages/aea/agent.py)

Option3: Step by step:
`pipenv shell`
`python templates/v1/basic.py --name my_agent --dashboard --expected-version-id tac_v1`.

The error is:

>Traceback (most recent call last):
> File "basic.py", line 27, in <module>
>    from tac.agents.participant.v1.base.strategy import RegisterAs, SearchFor
>  File "/home/g2-test/Desktop/Agent-rameworks/github-repos/TAC/agents-tac/tac/agents/participant/v1/base/strategy.py", line >27, in <module>
>    from aea.protocols.oef.models import Description
>ModuleNotFoundError: No module named 'aea.protocols.oef'

my aea version is 0.9.0
OS: Ubuntu 18.04

Hope to hear from you soon.

**Comment by DavidMinarsch** [comment]
Hi @ashnaeldho , sorry for the delay. You seem to be using a virtual env which is setup for `aea` development with the current aea. For the tac, you need to follow the steps under `Preliminary` and `Dependencies`. In particular, you need to create a new virtual environment with the correct dependencies. I'll confirm the steps myself tomorrow.
